version: "3.9"
name: todo-app

services:
  database:
    image: postgres:alpine
    container_name: database
    environment:
      POSTGRES_DB: db_todo
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
    ports:
      - "5432:5432"
    networks:
      - todo-app
    healthcheck:
      interval: 5s
      test: [ "CMD-SHELL", "pg_isready -U todo" ]

  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_USER: todo
      DB_PASSWORD: todo
      DB_NAME: db_todo
      DB_HOST: database
      DB_PORT: 5432
      SSL_MODE: disable
      WEB_SERVER_PORT: 8080
    networks:
      - todo-app

  migrate:
    image: arigaio/atlas:latest
    command: >
      migrate apply --url "postgres://todo:todo@database:5432/db_todo?sslmode=disable"
    networks:
      - todo-app
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./migrations/:/migrations

networks:
  todo-app:
    driver: bridge
