// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Todo struct {
	ID          uuid.UUID
	Title       string
	Description pgtype.Text
	Completed   bool
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}
