// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"todoList/internal/entity"
	"todoList/internal/infra/database"
	"todoList/internal/infra/web"
	"todoList/sql/sqlc"
)

// Injectors from wire.go:

func NewTodoHandler(queries *db.Queries) *web.TodoHandler {
	todoRepository := database.NewTodoRepository(queries)
	todoHandler := web.NewTodoHandler(todoRepository)
	return todoHandler
}

// wire.go:

var setTodoRepositoryDependency = wire.NewSet(database.NewTodoRepository, wire.Bind(new(entity.TodoRepositoryInterface), new(*database.TodoRepository)))
